# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ba52a871f2e58b5f164d38608e5fbc5126dc745a6dbcc5f98424e0a7813714b6b82d3dd867add3cc722f7dc6026cdc0b776520b13bd6472543257eade89e6a

test:
  secret_key_base: ee26cb962e2578b30f46295e3911bdbcbff3803587f9a40726a5334441129cee7e6413f975769b0286628407b51adbf47f851cb6a38e56b1dc65c03e654e463c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
